language: objective-c  
osx_image: xcode11.5 
jobs:
  include:
    - stage: Tests 
      script:
       - xcodebuild test -project BussRoutesApp.xcodeproj -scheme BussRoutesApp -sdk iphonesimulator13.4 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4' | xpretty
    - stage: Deploy 
      script: 
       - xcodebuild build -project BussRoutesApp.xcodeproj -scheme BussRoutesApp -sdk iphonesimulator13.4 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4' -derivedDataPath build | xpretty
