os:
 — osx
language: objective-c
sudo: required
osx_image: xcode11.3
script:
 — set -o pipefail
 — xcodebuild test-without-building  -project task2.2Lab9.xcodeproj -scheme task2.2Lab9 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' -only-testing task2.2Lab9Tests/Test2Case/testExample
notifications:
 email:
 on_success: never
 on_failure: change
