language: objective-c  
osx_image: xcode11.5 
xcode_project: task2.2Lab9.xcodeproj 
xcode_scheme: FastTests
xcode_sdk: iphonesimulator13.5 
xcode_destination: 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
script:
-o pipefail && xcodebuild -project task2.2Lab9.xcodeproj -scheme FastTests -sdk iphonesimulator13.5 -destination platform\=iOS\ Simulator,name\=iPhone\ 11,OS\=13.5 test-without-building | xcpretty
