language: objective-c  
osx_image: xcode11.5 
xcode_project: task2.2Lab9.xcodeproj 
xcode_scheme: task2.2Lab9 
xcode_sdk: iphonesimulator13.5 
xcode_destination: 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
script:
 — set -o pipefail
 — xcodebuild test-without-building  -project task2.2Lab9.xcodeproj -scheme task2.2Lab9 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' -only-testing task2.2Lab9Tests/Test2Case/testExample
