language: objective-c  
osx_image: xcode11.5 
xcode_project: task2.2Lab9.xcodeproj 
xcode_scheme: task2.2Lab9 
xcode_sdk: iphonesimulator13.5 
destination: 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
