language: objective-c  
osx_image: xcode11.5 
script:
 - xcodebuild test-without-building  -project task2.2Lab9 -scema task2.2Lab9 -sdk iphonesimulator13.5 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5'
 - xcodebuild build -project task2.2Lab9.xcodeproj -scheme task2.2Lab9 -sdk iphonesimulator13.5 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' -derivedDataPath build

