language: objective-c  
osx_image: xcode11.5 
script:
 -set -o pipefail && xcodebuild -project task2.2Lab9.xcodeproj -scheme FastTests -sdk iphonesimulator13.5 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' build test | xcpretty
